---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6
  - name: centos-7.3
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[augeas::geminstall]
      - recipe[augeas::test]
    attributes:
      augeas:
        build-essential: true
