---
driver:
  name: docker
driver_config:
  use_sudo: false

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.4
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: debian-7.4

suites:
  - name: default
    run_list:
      - recipe[augeas::geminstall]
      - recipe[augeas::test]
    attributes:
