---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 16.6.10

platforms:
  - name: centos-6
  - name: centos-7
  - name: ubuntu-18.04
  - name: ubuntu-20.04
  - name: freebsd-11
  - name: freebsd-12


suites:
  - name: default
    run_list:
      - recipe[augeas::geminstall]
      - recipe[augeas::test]
    attributes:
      augeas:
        build_essential: true
