---
driver:
  name: docker

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[augeas::geminstall]
      - recipe[augeas::test]
    attributes:
