---
AllCops:
  Exclude:
    - 'vendor/**'
    - '**/metadata.rb'
    - 'Guardfile'
    - 'Vagrantfile'
    - 'Gemfile'
SpaceAfterComma:
  Enabled: false
Encoding:
  Enabled: false
WordArray:
  Enabled: false
ClassLength:
  Enabled: false
MethodLength:
  Enabled: false
LineLength:
  Enabled: false
RedundantReturn:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
