source 'https://rubygems.org'

gem 'chef','~>11'
gem 'rake'
gem "berkshelf", '~>3'
gem 'test-kitchen', git: 'https://github.com/test-kitchen/test-kitchen.git', ref: '3d3d024443e89bb5a7182'
gem 'kitchen-vagrant'
gem 'kitchen-docker'
gem 'rubocop'
gem 'ruby-augeas'
gem 'minitest'
gem 'guard-rubocop'
gem 'guard'
gem 'guard-minitest'
gem 'guard-kitchen'
gem 'thor-scmversion'
