source 'https://rubygems.org'

gem 'berkshelf','~>2'
gem 'test-kitchen'
gem 'kitchen-vagrant'
gem 'kitchen-docker'
gem 'rake'
gem 'ruby-augeas'
gem 'guard'
gem 'guard-minitest'
gem 'guard-kitchen'
gem 'chef','~>11'
gem 'rubocop'
gem 'guard-rubocop'
