source 'https://rubygems.org'

gem 'chef','~>11'
gem 'rake'
gem "berkshelf", '~>3'
gem 'test-kitchen'
gem 'kitchen-vagrant'
gem 'kitchen-docker'
gem 'rubocop'
gem 'ruby-augeas'
gem 'minitest'
gem 'guard-rubocop'
gem 'guard'
gem 'guard-minitest'
gem 'guard-kitchen'
gem 'thor-scmversion'
